apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-service
  name: test-service
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
    NodePort: 30008
  selector:
    app: test-service
  type: NodePort
